// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarMonitor.Infrastructure.Data;

#nullable disable

namespace SolarMonitor.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313175226_SeedInitialPanels")]
    partial class SeedInitialPanels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarMonitor.Domain.Entities.Panel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Panels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Brand = "SunPower",
                            InstallationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Maxeon 3",
                            Type = "Monocrystalline"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Brand = "LG",
                            InstallationDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "NeON 2",
                            Type = "Monocrystalline"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Brand = "Canadian Solar",
                            InstallationDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "HiKu",
                            Type = "Polycrystalline"
                        });
                });

            modelBuilder.Entity("SolarMonitor.Domain.Entities.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("Voltage")
                        .HasColumnType("float");

                    b.Property<double>("Watts")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.ToTable("Readings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PanelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Voltage = 48.200000000000003,
                            Watts = 350.5
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PanelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Timestamp = new DateTime(2026, 3, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Voltage = 48.5,
                            Watts = 375.0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            PanelId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Timestamp = new DateTime(2026, 3, 13, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Voltage = 47.799999999999997,
                            Watts = 320.0
                        });
                });

            modelBuilder.Entity("SolarMonitor.Domain.Entities.Reading", b =>
                {
                    b.HasOne("SolarMonitor.Domain.Entities.Panel", null)
                        .WithMany("Readings")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolarMonitor.Domain.Entities.Panel", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
