version: '3.8'

services:
  # 1. Our SolarMonitor Web API
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:8080" # Map PC port 5005 to Container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db # Tell Docker to start the database before starting the API

  # 2. The SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433" # Standard SQL Server port
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SolarMonitor_StrongPass123!

  # 3. Prometheus (Metrics Database)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # 4. Jaeger (Distributed Tracing)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger Web UI
      - "4317:4317"   # OTLP gRPC receiver for traces

  # 5. Grafana (Dashboards)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana Web UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # 6. Redis (In-Memory Cache)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"