events { 
    worker_connections 1024; 
}

http {
    # This block defines our two environments. 
    # The active one is uncommented. The idle one is commented out.
    upstream solarmonitor_api {
        server api-blue:8080;
        # server api-green:8080;
    }

    server {
        listen 80;

        location / {
            # Nginx blindly forwards all traffic to whatever is active in the upstream block
            proxy_pass http://solarmonitor_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}