events { 
    worker_connections 1024; 
}

http {
    upstream solarmonitor_api {
        server api-blue:8080;
        # server api-green:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://solarmonitor_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # The Magic SignalR WebSocket Headers!
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }
}